/**
 * EDTTI catalog — single source of truth for the wipe-and-reseed.
 *
 * Transcribed VERBATIM from "COURSES PRESENT AND THEIR CODES.docx" (the
 * authoritative document). Department + course names use the corrected
 * spellings from the program-code table; unit names are kept exactly as they
 * appear in the document (uppercase) so no data is altered.
 *
 * Shape:
 *   DEPARTMENTS: [{ name, textCode, code }]
 *       - textCode: snake_case key stored on students.department / users.department
 *       - code:     2-letter departments.code (matches utils/formatters DEPT_TEXT_TO_SHORT)
 *   COURSES: [{ name, codePrefix, department (textCode), levels:[..], modules:{ n:[unitName,..] } }]
 *       - one program is created PER level: code = `${codePrefix}${level}`,
 *         name = `${name} Level ${level}`.
 *
 * Module → level visibility is the runtime concern (see utils/studentHelpers
 * MAX_MODULE_BY_LEVEL). Units are seeded per level (duplicate-per-level): a
 * level program holds modules 1..cap(level); the highest-level program of a
 * course holds ALL its modules so nothing is lost.
 */

const DEPARTMENTS = [
    { name: 'Agriculture',                    textCode: 'agriculture',           code: 'AG' },
    { name: 'Applied Science',                textCode: 'applied_science',       code: 'AS' },
    { name: 'Computing and Informatics',      textCode: 'computing_informatics', code: 'IT' },
    { name: 'Building and Civil Engineering', textCode: 'building_civil',        code: 'BC' },
    { name: 'Business and Liberal Studies',   textCode: 'business_liberal',      code: 'BL' },
    { name: 'Electromechanical',              textCode: 'electromechanical',     code: 'EM' },
    { name: 'Hospitality',                    textCode: 'hospitality',           code: 'HO' },
];

const COURSES = [
    // ---------------------------------------------------------------- Agriculture
    {
        name: 'Agricultural Extension',
        codePrefix: 'GA',
        department: 'agriculture',
        levels: [4, 5, 6],
        modules: {
            1: ['OPERATE FARM MACHINERY', 'PRODUCE ANNUAL CROPS', 'PRODUCE HORTICULTURAL CROPS'],
            2: ['CONSERVE WATER IN FARM', 'PRODUCE NON-RUMINANT ANIMALS', 'PRODUCE RUMINANT ANIMALS'],
            3: ['APPLY COMMUNICATION SKILLS', 'APPLY DIGITAL LITERACY', 'CARRY OUT BEE PRODUCTION', 'CARRY OUT FISH FARMING', 'PRODUCE PERENNIAL CROPS'],
            4: ['APPLY ANIMAL ANATOMY AND PHYSIOLOGY', 'APPLY ENTREPRENEURIAL SKILLS', 'APPLY WORK ETHICS AND PRACTICES', 'CARRY OUT EXTENSION SERVICES', 'PRODUCE FORAGE CROPS'],
            5: ['APPLY INORGANIC AND ORGANIC CHEMISTRY PRINCIPLES', 'APPLY SOIL SCIENCE PRINCIPLES', 'ESTABLISH FARM STRUCTURE'],
            6: ['APPLY FARM MANAGEMENT PRINCIPLES', 'APPLY GENETICS PRINCIPLES', 'SCIENTIFIC RESEARCH'],
        },
    },

    // ------------------------------------------------------------- Applied Science
    {
        name: 'Analytical Chemistry',
        codePrefix: 'AC',
        department: 'applied_science',
        levels: [6],
        modules: {
            1: ['PERFORM CHEMICAL SEPARATION', 'PREPARE CHEMICAL SAMPLES'],
            2: ['APPLY MATHEMATICS FOR SCIENCE', 'APPLY ORGANIC CHEMISTRY PRINCIPLES', 'PERFORM BIOCHEMICAL ANALYSIS'],
            3: ['APPLY COMMUNICATION SKILLS', 'APPLY INORGANIC CHEMISTRY PRINCIPLES', 'PERFORM CLASSICAL ANALYSIS TECHNIQUES'],
            4: ['APPLY DIGITAL LITERACY', 'APPLY PHYSICS PRINCIPLES', 'PERFORM INSTRUMENTAL ANALYSIS'],
            5: ['APPLY PHYSICAL CHEMISTRY PRINCIPLES', 'APPLY WORK ETHICS AND PRACTICES', 'PERFORM INDUSTRIAL CHEMISTRY ANALYSIS'],
            6: ['APPLY ENTREPRENEURIAL SKILLS', 'APPLY RESEARCH METHODS', 'PERFORM QUALITY ASSURANCE AND CONTROL'],
        },
    },
    {
        name: 'Applied Biology',
        codePrefix: 'AB',
        department: 'applied_science',
        levels: [6],
        modules: {
            1: ['APPLY COMMUNICATION SKILLS', 'APPLY LABORATORY PRACTICE PRINCIPLES', 'APPLY MATHEMATICS FOR SCIENCE', 'CONDUCT HISTOLOGICAL AND CYTOLOGICAL TECHNIQUES'],
            2: ['APPLY ANIMAL ANATOMY AND PHYSIOLOGY CONCEPTS', 'CARRY OUT LABORATORY ANIMAL HUSBANDRY', 'CARRY OUT PLANT HUSBANDRY'],
            3: ['APPLY TAXONOMICAL CONCEPTS', 'PERFORM ECOLOGICAL TECHNIQUES', 'PERFORM MUSEUM HERBARIUM AQUARIUM AND VIVARIUM TECHNIQUES'],
            4: ['APPLY DIGITAL LITERACY', 'PERFORM IMMUNOLOGICAL TECHNIQUES', 'PERFORM MICROBIOLOGICAL TECHNIQUES'],
            5: ['APPLY WORK ETHICS AND PRACTICES', 'CONDUCT SCIENTIFIC RESEARCH', 'PERFORM PARASITOLOGICAL AND ENTOMOLOGICAL TECHNIQUES'],
            6: ['APPLY ENTREPRENEURIAL SKILLS', 'APPLY GENETICS PRINCIPLES', 'CONDUCT BIOCHEMICAL ANALYSIS', 'PERFORM PHARMACOLOGICAL AND TOXICOLOGICAL TECHNIQUES'],
        },
    },
    {
        name: 'Science Laboratory Technology',
        codePrefix: 'SLT',
        department: 'applied_science',
        levels: [5, 6],
        modules: {
            1: ['APPLY COMMUNICATION SKILLS', 'APPLY GENERAL SCIENCE PRINCIPLES', 'PERFORM BIOLOGY TECHNIQUES', 'PERFORM STANDARD LABORATORY PRACTICES'],
            2: ['APPLY DIGITAL LITERACY', 'APPLY MATHEMATICS FOR SCIENCE', 'MAINTAIN LABORATORY EQUIPMENT', 'PERFORM CHEMISTRY TECHNIQUES'],
            3: ['APPLY ENTREPRENEURIAL SKILLS', 'APPLY WORK ETHICS AND PRACTICES', 'CONDUCT SCIENCE LABORATORY RESEARCH', 'PERFORM PHYSICS TECHNIQUES'],
            4: ['APPLY CHEMISTRY PRINCIPLES', 'PERFORM AQUARIUM VIVARIUM AND HERBARIUM TECHNIQUES', 'PERFORM CHEMICAL ANALYSES'],
            5: ['APPLY LABORATORY AND MANAGEMENT PRACTICES', 'APPLY PHYSICS PRINCIPLES', 'CARRY OUT CYTO-HISTOLOGICAL AND IMMUNOLOGICAL TECHNIQUES', 'TEST MATERIAL PROPERTIES'],
            6: ['APPLY BIOLOGY PRINCIPLES', 'CONDUCT MICROBIOLOGICAL TESTS', 'MEASURE PHYSICAL QUANTITIES', 'PERFORM CHEMISTRY INSTRUMENTATION TECHNIQUES'],
        },
    },

    // ----------------------------------------------------- Computing and Informatics
    {
        name: 'ICT',
        codePrefix: 'ICT',
        department: 'computing_informatics',
        levels: [4, 5, 6],
        modules: {
            1: ['APPLY COMMUNICATION SKILLS', 'APPLY ENTREPRENEURIAL SKILLS', 'APPLY WORK ETHICS AND PRACTICES'],
            2: ['APPLY BASIC ELECTRONICS', 'APPLY COMPUTER PROGRAMMING PRINCIPLES', 'APPLY DISCRETE MATHEMATICAL CONCEPTS', 'PERFORM SYSTEM ANALYSIS AND DESIGN'],
            3: ['DEVELOP DESKTOP APPLICATION', 'DEVELOP WEBSITE APPLICATION', 'INSTALL COMPUTER SOFTWARE'],
            4: ['MANAGE COMPUTERIZED DATABASE SYSTEMS', 'MANAGE ICT SECURITY', 'PERFORM COMPUTER ESSENTIALS'],
            5: ['PERFORM COMPUTER NETWORK SETUP', 'PERFORM COMPUTER OPERATIONS', 'PERFORM COMPUTER REPAIR AND MAINTENANCE', 'PERFORM NETWORK DESIGN AND MANAGEMENT'],
        },
    },
    {
        name: 'Library and Information Science',
        codePrefix: 'LIS',
        department: 'computing_informatics',
        levels: [5, 6],
        modules: {
            1: ['APPLY DIGITAL LITERACY', 'MAINTAIN ORGANIZATIONAL RECORDS', 'PERFORM INFORMATION COLLECTION DEVELOPMENT', 'PROCESS INFORMATION MATERIALS'],
            2: ['APPLY COMMUNICATION SKILLS', 'APPLY WORKPLACE ETHICS AND PRACTICES', 'PERFORM CIRCULATION DUTIES', 'PERFORM RESTORATION OF INFORMATION MATERIALS'],
            3: ['APPLY ENTREPRENEURIAL SKILLS', 'APPLY MANAGEMENT PRINCIPLES', 'PERFORM LIBRARY CATALOGUING', 'PERFORM SYSTEM ANALYSIS AND DESIGN'],
            4: ['CONDUCT LIBRARY AND INFORMATION MANAGEMENT RESEARCH', 'MANAGE LIBRARY INFORMATION RESOURCES', 'PRESERVE LIBRARY INFORMATION MATERIALS'],
            5: ['CONDUCT INDEXING AND ABSTRACTING', 'MANAGE DIGITAL REPOSITORY', 'MANAGE ORGANIZATIONAL RECORDS'],
        },
    },

    // ------------------------------------------------ Building and Civil Engineering
    {
        name: 'Building Technology',
        codePrefix: 'BT',
        department: 'building_civil',
        levels: [3, 4, 5, 6],
        modules: {
            1: ['PERFORM MASONRY WORKS', 'PERFORM MASONRY WORKS FINISHES I', 'PRODUCE MASONRY PRODUCTS'],
            2: ['PERFORM BUILDING SITE PRELIMINARY WORKS I', 'PERFORM BUILDING TEMPORARY WORKS'],
            3: ['APPLY BASIC MATHEMATICS I', 'APPLY COMMUNICATION SKILLS', 'APPLY DIGITAL LITERACY', 'APPLY TECHNICAL DRAWING', 'EXECUTE EXTERNAL WORKS', 'INSTALL DOORS AND WINDOWS', 'PERFORM BUILDING SUBSTRUCTURE WORKS'],
            4: ['APPLY BASIC MATHEMATICS II', 'APPLY CONSTRUCTION MATERIAL SCIENCE', 'APPLY ENTREPRENEURIAL SKILLS', 'APPLY WORK ETHICS AND PRACTICES', 'PERFORM BUILDING SUPERSTRUCTURE WORKS', 'PERFORM MASONRY WORKS FINISHES II'],
            5: ['APPLY STRUCTURAL ANALYSIS PRINCIPLES I', 'CARRY OUT ROOF CONSTRUCTION WORK', 'PERFORM BUILDING SITE PRELIMINARY WORKS II', 'PERFORM BUILDING SUPER STRUCTURE WORKS II'],
            6: ['APPLY ENGINEERING SURVEY PRINCIPLES I', 'APPLY MEASUREMENT ESTIMATION AND COSTING OF WORKS I', 'APPLY STRUCTURAL ANALYSIS PRINCIPLES II', 'APPLY WORKSHOP TECHNOLOGY PRACTICES', 'CARRY OUT BUILDING FINISHES III'],
            7: ['APPLY ENGINEERING SURVEY PRINCIPLES II', 'APPLY MEASUREMENT ESTIMATION AND COSTING OF WORKS II', 'MANAGE BUILDING CONSTRUCTION WORKS', 'PREPARE BUILDING DRAWING'],
        },
    },
    {
        name: 'Plumbing',
        codePrefix: 'PL',
        department: 'building_civil',
        levels: [3, 4, 5],
        modules: {
            1: ['INSTALL DRAINAGE SYSTEM I', 'INSTALL SANITARY APPLIANCES I', 'INSTALL WATER SUPPLY SYSTEM I'],
            2: ['INSTALL DRAINAGE SYSTEM II', 'INSTALL RAINWATER HARVESTING SYSTEM I', 'INSTALL SANITARY APPLIANCES II', 'INSTALL WATER SUPPLY SYSTEM II'],
            3: ['APPLY BASIC MATHEMATICS PRINCIPLES', 'APPLY COMMUNICATION SKILLS', 'APPLY DIGITAL LITERACY', 'INSTALL WATER STORAGE SYSTEM', 'INSTALL WATER SUPPLY SYSTEM III'],
            4: ['APPLY CONSTRUCTION MATERIAL SCIENCE', 'APPLY ENTREPRENEURIAL SKILLS', 'APPLY WORK ETHICS AND PRACTICES', 'DEMONSTRATE WORKSHOP TECHNOLOGY SKILLS', 'INSTALL FIRE CONTROL SYSTEMS', 'PREPARE AND INTERPRET TECHNICAL DRAWINGS'],
        },
    },

    // ------------------------------------------------- Business and Liberal Studies
    {
        name: 'Business Management',
        codePrefix: 'BM',
        department: 'business_liberal',
        levels: [5, 6],
        modules: {
            1: ['APPLY BUSINESS COMMUNICATION', 'APPLY FINANCIAL ACCOUNTING SKILLS', 'APPLY WORK ETHICS AND PRACTICES', 'PERFORM SALES ACTIVITIES'],
            2: ['APPLY DIGITAL LITERACY', 'APPLY ECONOMICS SKILLS', 'APPLY ENTREPRENEURIAL SKILLS', 'PERFORM PURCHASING SKILLS'],
            3: ['APPLY BUSINESS MATHEMATICS AND STATISTICS', 'APPLY MANAGEMENT SKILLS', 'APPLY PRINCIPLES OF COMMERCIAL LAW', 'PERFORM ADMINISTRATIVE ASSISTANT DUTIES', 'PERFORM STAFFING ACTIVITIES'],
            4: ['CONDUCT RESEARCH PROJECT', 'MANAGE MARKETING ACTIVITIES', 'PERFORM HUMAN RESOURCE ACTIVITIES', 'PERFORM SUPPLY CHAIN ACTIVITIES'],
            5: ['CARRY OUT ACCOUNTING OPERATIONS', 'DEVELOP ORGANIZATIONAL STRATEGIC PLAN', 'MANAGE BUSINESS RISKS'],
        },
    },
    {
        name: 'Storekeeping',
        codePrefix: 'SK',
        department: 'business_liberal',
        levels: [4],
        modules: {
            1: ['CLASSIFY AND CODIFY PROCURED GOODS', 'MANAGE STORAGE OF GOODS', 'RECEIVE DELIVERED GOODS'],
            2: ['ISSUE AND DISPATCH GOODS', 'MANAGE STORES SAFETY AND SECURITY', 'PRESERVE STORED GOODS'],
        },
    },
    {
        name: 'Office Administration',
        codePrefix: 'OA',
        department: 'business_liberal',
        levels: [4, 5, 6],
        modules: {
            1: ['APPLY SHORTHAND SKILLS I', 'HANDLE CUSTOMER CARE DUTIES', 'HANDLE OFFICE CORRESPONDENCE', 'HANDLE OFFICE ERRANDS', 'PROCESS OFFICE DOCUMENTS I'],
            2: ['APPLY SHORTHAND SKILLS II', 'COORDINATE OFFICE REPAIRS AND MAINTENANCE', 'MAINTAIN OFFICE PAPER RECORDS', 'MANAGE TELEPHONE CALLS', 'PROCESS OFFICE DOCUMENTS II', 'UNDERTAKE BUSINESS COMMUNICATION'],
            3: ['APPLY ICT SKILLS', 'APPLY INTERMEDIATE SHORTHAND SKILLS', 'APPLY WORK ETHICS AND PRACTICES', 'PROCESS INTERMEDIATE OFFICE DOCUMENTS PROCESSING'],
            4: ['APPLY COMMERCE PRINCIPLES', 'APPLY ENTREPRENEURIAL SKILLS', 'COORDINATE OFFICIAL MEETINGS', 'MANAGE OFFICE ADMINISTRATIVE DUTIES', 'MANAGE OFFICE SECURITY'],
            5: ['APPLY ADVANCED SHORTHAND SKILLS 1', 'APPLY FINANCIAL ACCOUNTING SKILLS', 'APPLY MANAGEMENT PRINCIPLES', 'COORDINATE TRAVEL ARRANGEMENTS', 'PROCESS ADVANCED OFFICE DOCUMENTS I'],
            6: ['APPLY ADVANCED SHORTHAND SKILLS II', 'APPLY ECONOMICS PRINCIPLES', 'APPLY PRINCIPLES OF COMMERCIAL LAW', 'CONDUCT RESEARCH PROJECT', 'PROCESS ADVANCED OFFICE DOCUMENTS II'],
        },
    },
    {
        name: 'Social Work',
        codePrefix: 'SW',
        department: 'business_liberal',
        levels: [5, 6],
        modules: {
            1: ['APPLY COMMUNICATION SKILLS', 'CONDUCT CHILD WELFARE PROGRAMMES', 'CONDUCT HOME BASED CARE', 'MANAGE COMMUNITY-BASED GROUPS'],
            2: ['APPLY DIGITAL LITERACY', 'CONDUCT COMMUNITY EMPOWERMENT', 'CONDUCT SOCIAL WORK CASE MANAGEMENT', 'PROVIDE PSYCHO-SOCIAL SUPPORT'],
            3: ['APPLY WORK ETHICS AND PRACTICES', 'CARRY OUT ADVOCACY AND LOBBYING', 'COORDINATE DISASTER MANAGEMENT'],
            4: ['CARRY OUT RESOURCE MOBILIZATION', 'COORDINATE REHABILITATION AND RE-INTEGRATION PROGRAMMES', 'MANAGE SOCIAL WORK SERVICES'],
            5: ['APPLY ENTREPRENEURIAL SKILLS', 'CONDUCT SOCIAL POLICY ADMINISTRATION', 'CONDUCT SOCIAL RESEARCH WORK', 'MANAGE COMMUNITY PROJECTS'],
        },
    },

    // ---------------------------------------------------------- Electromechanical
    {
        name: 'Electrical Engineering',
        codePrefix: 'EE',
        department: 'electromechanical',
        levels: [3, 4, 5, 6],
        modules: {
            1: ['INSTALL CONDUIT SYSTEM', 'INSTALL PVC SHEATHED CABLE SYSTEM', 'INSTALL TRUNKING SYSTEM'],
            2: ['INSTALL STAND-ALONE SOLAR PV SYSTEMS', 'PERFORM BELL AND ALARM INSTALLATION', 'WIND ELECTRICAL MACHINE'],
            3: ['APPLY BASIC ELECTRICAL PRINCIPLES', 'APPLY COMMUNICATION SKILLS', 'APPLY DIGITAL LITERACY', 'PERFORM ELECTRICAL INSTALLATION', 'PREPARE TECHNICAL DRAWINGS'],
            4: ['APPLY ANALOGUE ELECTRONICS I', 'APPLY DIGITAL ELECTRONICS I', 'APPLY ENGINEERING TECHNICIAN MATHEMATICS I', 'APPLY WORK ETHICS AND PRACTICES', 'PERFORM SECURITY SYSTEM INSTALLATION'],
            5: ['APPLY ANALOGUE ELECTRONICS II', 'APPLY DIGITAL ELECTRONICS II', 'APPLY ENGINEERING TECHNICIAN MATHEMATICS II', 'APPLY ENTREPRENEURIAL SKILLS', 'INSTALL SOLAR PV SYSTEMS', 'PERFORM ELECTRICAL MACHINE INSTALLATION'],
            6: ['APPLY ELECTRICAL PRINCIPLES I', 'APPLY ENGINEERING TECHNICIAN MATHEMATICS III', 'APPLY MICRO CONTROL SYSTEMS', 'INSTALL ELECTRICAL POWER LINES'],
            7: ['APPLY CONTROL SYSTEMS', 'APPLY ELECTRICAL PRINCIPLES II', 'APPLY ENGINEERING TECHNICIAN MATHEMATICS IV', 'AUTOMATE ELECTRICAL SYSTEMS'],
            8: ['APPLY RESEARCH METHODS', 'FABRICATE POWER ELECTRONICS CIRCUITS', 'PERFORM ELECTRICAL MEASUREMENT AND FAULT DIAGNOSIS', 'SUPERVISE ELECTRICAL PROJECT'],
        },
    },
    {
        name: 'Automotive Engineering',
        codePrefix: 'MA',
        department: 'electromechanical',
        levels: [3, 4, 5, 6],
        modules: {
            1: ['MAINTAIN VEHICLE BRAKING SYSTEM', 'MAINTAIN VEHICLE PETROL ENGINE'],
            2: ['MAINTAIN VEHICLE DIESEL ENGINE', 'MAINTAIN VEHICLE SUSPENSION AND STEERING SYSTEM'],
            3: ['APPLY COMMUNICATION SKILLS', 'APPLY MATHEMATICS', 'APPLY TECHNICAL DRAWINGS', 'APPLY WORK ETHICS AND PRACTICES', 'MAINTAIN AUTOMOTIVE ELECTRICAL SYSTEMS', 'MAINTAIN VEHICLE FUEL SYSTEM'],
            4: ['APPLY DIGITAL LITERACY', 'APPLY ELECTRICAL AND ELECTRONICS PRINCIPLES', 'APPLY ENTREPRENEURIAL SKILLS', 'APPLY MECHANICAL SCIENCE', 'APPLY WORKSHOP TECHNOLOGY', 'MAINTAIN VEHICLE TRANSMISSION SYSTEM'],
            5: ['APPLY ENGINEERING MATHEMATICS', 'MAINTAIN HYBRID AND ELECTRIC VEHICLE', 'PERFORM COMPUTER AIDED DRAWING'],
            6: ['APPLY ENGINEERING MECHANICS', 'MAINTAIN VEHICLE SAFETY AND SECURITY SYSTEM'],
            7: ['APPLY THERMODYNAMICS AND FLUID MECHANICS', 'MAINTAIN VEHICLE COMFORT SYSTEM'],
        },
    },

    // ----------------------------------------------------------------- Hospitality
    {
        name: 'Food and Beverage',
        codePrefix: 'FB',
        department: 'hospitality',
        levels: [4, 5, 6],
        modules: {
            1: ['PERFORM FOOD AND BEVERAGE SERVICE TECHNIQUES I', 'PREPARE MOCKTAILS AND COCKTAILS I', 'SERVE FOOD AND BEVERAGE I'],
            2: ['PERFORM BANQUET AND EVENTS OPERATIONS I', 'PERFORM BAR KEEPING OPERATIONS I'],
            3: ['APPLY DIGITAL LITERACY', 'PREPARE DESSERTS II', 'PREPARE MAIN MEAL II', 'PREPARE STARTERS AND STARTER ACCOMPANIMENT II'],
            4: ['PREPARE PASTRIES II', 'PREPARE SPECIALTY DISHES II'],
            5: ['APPLY COMMUNICATION SKILLS', 'APPLY ENTREPRENEURIAL SKILLS', 'APPLY PRINCIPLES OF FOOD SCIENCE AND NUTRITION', 'APPLY WORK ETHICS AND PRACTICES', 'PERFORM FOOD AND BEVERAGE COST CONTROL'],
            6: ['APPLY DIET THERAPY', 'APPLY MARKETING SKILLS', 'PERFORM ACCOUNTING OPERATIONS'],
            7: ['APPLY PRINCIPLES OF MANAGEMENT IN FOOD AND BEVERAGE OPERATIONS', 'UNDERTAKE HOSPITALITY RESEARCH'],
        },
    },
    {
        name: 'Fashion and Design',
        codePrefix: 'FD',
        department: 'hospitality',
        levels: [3, 4, 5, 6],
        modules: {
            1: ["CONSTRUCT BASIC GENT'S GARMENTS", "CONSTRUCT BASIC LADIES' GARMENTS", 'PERFORM SEWING MACHINE OPERATIONS'],
            2: ['PRODUCE DECORATED FABRICS (TIE & DYE AND PRINTING)', 'PRODUCE STYLED GARMENTS'],
            3: ['APPLY COMMUNICATION SKILLS', 'APPLY DIGITAL LITERACY', 'APPLY FASHION DESIGN AND SKETCHING', 'APPLY TEXTILE MATERIALS PRINCIPLES', 'PRODUCE DECORATED FABRICS (BATIK AND EMBROIDERY)', "PRODUCE LADIES' WEAR"],
            4: ['APPLY ENTREPRENEURIAL SKILLS', 'APPLY PATTERN CONSTRUCTION PRINCIPLES', 'APPLY WORK ETHICS AND PRACTICES', "PRODUCE GENTS' WEAR"],
            5: ['APPLY GARMENT CUTTING PRINCIPLES', 'APPLY INDUSTRIAL ORGANISATION MANAGEMENT', "PRODUCE CHILDREN'S WEAR"],
            6: ['APPLY COMPUTER AIDED DESIGN', 'APPLY QUALITY CONTROL PRINCIPLES', 'PRODUCE FASHION ACCESSORIES'],
            7: ['APPLY RESEARCH METHODS', 'PRODUCE LINGERIE WEAR', 'PRODUCE OCCASION WEAR', 'PRODUCE SPORTS WEAR', 'PRODUCE UNIFORM WEAR'],
        },
    },
    {
        name: 'Cosmetology',
        codePrefix: 'COS',
        department: 'hospitality',
        levels: [3, 4, 5, 6],
        modules: {
            1: ['CONDUCT BARBERING SERVICE', 'PROVIDE MANICURE AND PEDICURE', 'PROVIDE PLAITING AND BRAIDING'],
            2: ['PERFORM HAIR STYLING SERVICES', 'PROVIDE HAIR ADDITIONS SERVICES', 'PROVIDE MAKE UP SERVICES'],
            3: ['APPLY COMMUNICATION SKILLS', 'APPLY DIGITAL LITERACY', 'PERFORM NAIL CARE SERVICE', 'PROVIDE DREAD LOCKING SERVICE', 'PROVIDE HAIR REMOVAL SERVICE'],
            4: ['APPLY ENTREPRENEURIAL SKILLS', 'APPLY WORK ETHICS PRACTICES', 'CONDUCT HAIR CUTTING SERVICE', 'PROVIDE FACIAL SKIN CARE SERVICE'],
            5: ['MANAGE HAIR AND BEAUTY PARLOR', 'PERFORM HAIR CHEMICAL REFORMATION', 'PRODUCE HAIR EXTENSIONS'],
            6: ['CARRY OUT COSMETOLOGY RESEARCH', 'PROVIDE BODY MASSAGE', 'PROVIDE HAIR COLOURING'],
        },
    },
    {
        name: 'Tour and Travel Management',
        codePrefix: 'TTM',
        department: 'hospitality',
        levels: [5, 6],
        modules: {
            1: ['APPLY COMMUNICATION SKILLS', 'APPLY DIGITAL LITERACY', 'APPLY TOURISM INDUSTRY KNOWLEDGE', 'PERFORM TOUR & TRAVEL BOOKING AND RESERVATIONS'],
            2: ['APPLY WORK ETHICS AND PRACTICES', 'CONDUCT TOURISM RESEARCH', 'PROCESS FLIGHT BOOKING/RESERVATION'],
            3: ['APPLY ENTREPRENEURIAL SKILLS', 'PERFORM TOUR GUIDE OPERATIONS'],
            4: ['APPLY BEGINNER FOREIGN LANGUAGE SKILLS', 'MANAGE TOURIST EXPERIENCE', 'PERFORM TOUR AND TRAVEL OPERATIONS'],
            5: ['APPLY INTERMEDIATE FOREIGN LANGUAGE SKILLS', 'MANAGE TOUR AND TRAVEL FINANCES'],
            6: ['CONDUCT TOUR MARKETING', 'MANAGE TOURIST SITE', 'PROMOTE RESPONSIBLE TOURISM'],
        },
    },
];

module.exports = { DEPARTMENTS, COURSES };
